name: GKE Release Bot (Codex)

on:
  schedule:
    - cron: "40 11 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Make script executable
        run: chmod +x scripts/run_codex.sh

      - name: Run Codex
        id: codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # CODEX_PROMPT: prompts/gke-latest.md   # uncomment if your prompt path differs
        run: scripts/run_codex.sh

      - name: Create PR
        if: steps.codex.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          # If your repo blocks GITHUB_TOKEN PRs, add a PAT secret and uncomment:
          # token: ${{ secrets.CREATE_PR_TOKEN }}
          commit-message: "chore(gke): add latest Stable R releases"
          title: "chore(gke): add latest Stable R releases"
          body: |
            Automated update of `GKEProjectReleases` (Stable channel only),
            using daily workflow and the prompt in `prompts/gke-latest.md`.
          branch: chore/gke-release-auto
          delete-branch: true
          signoff: true
