name: GKE Release Bot (Codex)

on:
  schedule:
    - cron: "40 11 * * *"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-map:
    runs-on: ubuntu-latest
    env:
      # Force Codex authentication & model so CI doesn't guess.
      CODEX_AUTH_METHOD: api-key
      CODEX_PROVIDER: openai
      CODEX_MODEL: gpt-4o-mini
      # If your account requires these, add as repo secrets and uncomment:
      # OPENAI_ORGANIZATION: ${{ secrets.OPENAI_ORGANIZATION }}
      # OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Set up Node
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Set up Go (for gofmt)
        uses: actions/setup-go@v5
        with: { go-version: "1.22.x" }

      - name: Install Codex
        run: |
          npm install -g @openai/codex
          codex --version

      - name: Run Codex (headless)
        id: codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          test -f prompts/gke-latest.md || { echo "prompt not found: prompts/gke-latest.md"; exit 2; }
          git reset --hard
          git clean -fd
          set +e
          OPENAI_API_KEY="$OPENAI_API_KEY" codex exec --full-auto "$(cat prompts/gke-latest.md)"
          CODE=$?
          set -e
          command -v gofmt >/dev/null 2>&1 && gofmt -s -w .
          if git diff --quiet; then
            echo "changed=0" >> "$GITHUB_OUTPUT"
          else
            echo "changed=1" >> "$GITHUB_OUTPUT"
          fi
          echo "status=${CODE}" >> "$GITHUB_OUTPUT"

      - name: Create PR
        if: steps.codex.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          # If your org blocks PRs from GITHUB_TOKEN, add a PAT and uncomment the next line:
          # token: ${{ secrets.CREATE_PR_TOKEN }}
          commit-message: "chore(gke): add latest Stable R releases"
          title: "chore(gke): add latest Stable R releases"
          body: |
            Automated update of `GKEProjectReleases` (Stable channel only),
            using daily workflow and the prompt in `prompts/gke-latest.md`.
          branch: chore/gke-release-auto
          delete-branch: true
          signoff: true

      - name: Fail if Codex errored without changes
        if: ${{ steps.codex.outputs.status != '0' && steps.codex.outputs.changed != '1' }}
        run: exit 1
